/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index.js";
import * as BrowserUse from "../index.js";
import * as core from "../../core/index.js";

export class PaymentRequiredError extends errors.BrowserUseError {
    constructor(body: BrowserUse.InsufficientCreditsError, rawResponse?: core.RawResponse) {
        super({
            message: "PaymentRequiredError",
            statusCode: 402,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, PaymentRequiredError.prototype);
    }
}
