/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {
 *         task: "task"
 *     }
 */
export interface CreateTaskRequest {
    systemPromptExtension?: string;
    task: string;
    sessionId?: string;
    startUrl?: string;
    maxAgentSteps?: number;
    structuredOutput?: string;
    includedFileNames?: string[];
    metadata?: Record<string, string | undefined>;
    secrets?: Record<string, string | undefined>;
    allowedDomains?: string[];
    persistenceProfileId?: string;
    agent?: BrowserUse.AgentSettings;
    proxy?: BrowserUse.ProxySettings;
    browser?: BrowserUse.BrowserSettings;
    highlightElements?: boolean;
}
