/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {
 *         action: "stop"
 *     }
 */
export interface UpdateTaskRequest {
    action: BrowserUse.TaskUpdateAction;
}
