/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * View model for account information
 *
 * Attributes:
 *     monthly_credits_balance_usd: The monthly credits balance in USD
 *     additional_credits_balance_usd: The additional credits balance in USD
 *     email: The email address of the user
 *     name: The name of the user
 *     signed_up_at: The date and time the user signed up
 */
export interface AccountView {
    monthlyCreditsBalanceUsd: number;
    additionalCreditsBalanceUsd: number;
    email?: string;
    name?: string;
    signedUpAt: string;
}
