/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * Agent settings
 *
 * Attributes:
 *         llm: The LLM model to use for the agent
 *         highlight_elements: Whether to highlight elements during agent interaction with the browser
 *         max_agent_steps: Maximum number of steps the agent can take before stopping
 *
 *         flash_mode: Whether flash mode is enabled
 *         thinking: Whether thinking mode is enabled
 *         vision: Whether vision capabilities are enabled
 *         custom_system_prompt_extension: Optional custom system prompt for the agent
 */
export interface AgentSettings {
    llm?: BrowserUse.SupportedLlMs;
    flashMode?: boolean;
    thinking?: boolean;
    vision?: boolean;
}
