/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Browser viewport and behavior settings
 *
 * Attributes:
 *         viewport_width: Browser viewport width in pixels
 *         viewport_height: Browser viewport height in pixels
 *         is_mobile: Whether the browser should be in mobile view
 *         store_cache: Whether to store browser cache
 */
export interface BrowserSettings {
    viewportWidth?: number;
    viewportHeight?: number;
    isMobile?: boolean;
    storeCache?: boolean;
}
