/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error response when download URL generation fails
 */
export interface DownloadUrlGenerationError {
    detail?: string;
}
