/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * View model for representing an output file generated by the agent
 *
 * Attributes:
 *         id: Unique identifier for the output file
 *         file_name: Name of the output file
 */
export interface FileView {
    id: string;
    fileName: string;
}
