/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error response when user has insufficient credits
 */
export interface InsufficientCreditsError {
    detail?: string;
}
