/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

export type NotFoundErrorBody = BrowserUse.TaskNotFoundError | BrowserUse.OutputFileNotFoundError;
