/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * Response model for paginated persistence profile list requests
 *
 * Attributes:
 *     items: List of persistence profile views for the current page
 */
export interface PersistenceProfileListResponse {
    items: BrowserUse.PersistenceProfileView[];
    totalItems: number;
    pageNumber: number;
    pageSize: number;
}
