/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error response when a persistence profile is not found
 */
export interface PersistenceProfileNotFoundError {
    detail?: string;
}
