/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * View model for representing a persistence profile
 *
 * Attributes:
 *     id: Unique identifier for the profile
 *
 *         last_used_at: Timestamp when the profile was last used
 *
 *     created_at: Timestamp when the profile was created
 *     updated_at: Timestamp when the profile was last updated
 */
export interface PersistenceProfileView {
    id: string;
    lastUsedAt?: string;
    createdAt: string;
    updatedAt: string;
}
