/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProxyCountryCode = "us" | "uk" | "fr" | "it" | "jp" | "au" | "de" | "fi" | "ca" | "in";
export const ProxyCountryCode = {
    Us: "us",
    Uk: "uk",
    Fr: "fr",
    It: "it",
    Jp: "jp",
    Au: "au",
    De: "de",
    Fi: "fi",
    Ca: "ca",
    In: "in",
} as const;
