/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * Proxy configuration settings
 *
 * Attributes:
 *         enable: Whether proxy is enabled
 *         proxy_country_code: Country code for proxy location
 *         ad_blocker: Whether ad blocking is enabled
 */
export interface ProxySettings {
    enable?: boolean;
    proxyCountryCode?: BrowserUse.ProxyCountryCode;
    adBlocker?: boolean;
}
