/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Available actions that can be performed on a session
 *
 * Attributes:
 *     STOP: Stop the session and all its associated tasks (cannot be undone)
 */
export type SessionUpdateAction = "stop";
