/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * Response model for paginated session list requests
 *
 * Attributes:
 *     items: List of session views for the current page
 */
export interface SessionListResponse {
    items: BrowserUse.SessionItemView[];
    totalItems: number;
    pageNumber: number;
    pageSize: number;
}
