/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error response when session already has a running task
 */
export interface SessionHasRunningTaskError {
    detail?: string;
}
