/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * View model for representing a session that a task belongs to
 *
 * Attributes:
 *         id: Unique identifier for the session
 *         status: Current status of the session (active/stopped)
 *         live_url: URL where the browser can be viewed live in real-time.
 *         started_at: Timestamp when the session was created and started.
 *         finished_at: Timestamp when the session was stopped (None if still active).
 */
export interface TaskSessionView {
    id: string;
    status: BrowserUse.TaskSessionStatus;
    liveUrl?: string;
    startedAt: string;
    finishedAt?: string;
}
