/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for log file requests
 *
 * Attributes:
 *     download_url: URL to download the log file
 */
export interface TaskLogFileResponse {
    downloadUrl: string;
}
