/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for output file requests
 *
 * Attributes:
 *         id: Unique identifier for the output file
 *         file_name: Name of the output file
 *     download_url: URL to download the output file
 */
export interface TaskOutputFileResponse {
    id: string;
    fileName: string;
    downloadUrl: string;
}
