/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for creating a task
 *
 * Attributes:
 *         id: Unique identifier for the created task
 *         session_id: The ID of the agent session this task belongs to
 */
export interface TaskCreatedResponse {
    id: string;
    sessionId: string;
}
