/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Enumeration of possible task execution states
 *
 * Attributes:
 *     STARTED: Task has been started and is currently running.
 *     PAUSED: Task execution has been temporarily paused (can be resumed)
 *     FINISHED: Task has finished and the agent has completed the task.
 *     STOPPED: Task execution has been manually stopped (cannot be resumed).
 */
export type TaskStatus = "started" | "paused" | "finished" | "stopped";
export const TaskStatus = {
    Started: "started",
    Paused: "paused",
    Finished: "finished",
    Stopped: "stopped",
} as const;
