/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * View model for representing a single step in a task's execution
 *
 * Attributes:
 *     number: Sequential step number within the task
 *     memory: Agent's memory at this step
 *     evaluation_previous_goal: Agent's evaluation of the previous goal completion
 *     next_goal: The goal for the next step
 *     url: Current URL the browser is on for this step
 *     screenshot_url: Optional URL to the screenshot taken at this step
 *     actions: List of stringified json actions performed by the agent in this step
 */
export interface TaskStepView {
    number: number;
    memory: string;
    evaluationPreviousGoal: string;
    nextGoal: string;
    url: string;
    screenshotUrl?: string;
    actions: string[];
}
