/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for user uploaded file requests
 *
 * Attributes:
 *         id: Unique identifier for the user uploaded file
 *         file_name: Name of the user uploaded file
 *     download_url: URL to download the user uploaded file
 */
export interface TaskUploadedFileResponse {
    id: string;
    fileName: string;
    downloadUrl: string;
}
