/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * Response model for paginated task list requests
 *
 * Attributes:
 *     items: List of task views for the current page
 */
export interface TaskListResponse {
    items: BrowserUse.TaskItemView[];
    totalItems: number;
    pageNumber: number;
    pageSize: number;
}
