/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Enumeration of possible (browser) session states
 *
 * Attributes:
 *     ACTIVE: Session is currently active and running (browser is running)
 *     STOPPED: Session has been stopped and is no longer active (browser is stopped)
 */
export type TaskSessionStatus = "active" | "stopped";
export const TaskSessionStatus = {
    Active: "active",
    Stopped: "stopped",
} as const;
