/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * View model for representing a task with its execution details
 *
 * Attributes:
 *     id: Unique identifier for the task
 *     session_id: ID of the session this task belongs to
 *     llm: The LLM model used for this task represented as a string
 *     task: The task prompt/instruction given to the agent
 *     status: Current status of the task execution
 *     started_at: Naive UTC timestamp when the task was started
 *     finished_at: Naive UTC timestamp when the task completed (None if still running)
 *     metadata: Optional additional metadata associated with the task set by the user
 *     is_scheduled: Whether this task was created as a scheduled task
 *     steps: Optional list of execution steps
 *     output: Final output/result of the task
 *     user_uploaded_files: Optional list of files uploaded by user for this task
 *     output_files: Optional list of files generated as output by this task
 *     browser_use_version: Version of browser-use used for this task (older tasks may not have this set)
 *         is_success: Whether the task was successful (self-reported by the agent)
 */
export interface TaskItemView {
    id: string;
    sessionId: string;
    llm: string;
    task: string;
    status: BrowserUse.TaskStatus;
    startedAt: string;
    finishedAt?: string;
    metadata?: Record<string, unknown>;
    isScheduled: boolean;
    output?: string;
    browserUseVersion?: string;
    isSuccess?: boolean;
}
