/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error response for unsupported content types
 */
export interface UnsupportedContentTypeError {
    detail?: string;
}
