/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for a presigned upload URL
 *
 * Attributes:
 *     url: The URL to upload the file to
 *     method: The HTTP method to use for the upload
 *     fields: The form fields to include in the upload request
 *     file_name: The name of the file to upload (should be referenced when user wants to use the file in a task)
 *     expires_in: The number of seconds until the presigned URL expires
 */
export interface UploadFilePresignedUrlResponse {
    url: string;
    method: "POST";
    fields: Record<string, string>;
    fileName: string;
    expiresIn: number;
}
