/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         fileName: "fileName",
 *         contentType: "image/jpg",
 *         sizeBytes: 1
 *     }
 */
export interface UploadFileRequest {
    fileName: string;
    contentType: UploadFileRequest.ContentType;
    sizeBytes: number;
}

export namespace UploadFileRequest {
    export type ContentType =
        | "image/jpg"
        | "image/jpeg"
        | "image/png"
        | "image/gif"
        | "image/webp"
        | "image/svg+xml"
        | "application/pdf"
        | "application/msword"
        | "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        | "application/vnd.ms-excel"
        | "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        | "text/plain"
        | "text/csv"
        | "text/markdown";
    export const ContentType = {
        ImageJpg: "image/jpg",
        ImageJpeg: "image/jpeg",
        ImagePng: "image/png",
        ImageGif: "image/gif",
        ImageWebp: "image/webp",
        ImageSvgXml: "image/svg+xml",
        ApplicationPdf: "application/pdf",
        ApplicationMsword: "application/msword",
        ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlDocument:
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ApplicationVndMsExcel: "application/vnd.ms-excel",
        ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlSheet:
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        TextPlain: "text/plain",
        TextCsv: "text/csv",
        TextMarkdown: "text/markdown",
    } as const;
}
