/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { BrowserUseClient } from "../../src/Client";

describe("Account", () => {
    test("getAccountMe", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            monthlyCreditsBalanceUsd: 1.1,
            additionalCreditsBalanceUsd: 1.1,
            email: "email",
            name: "name",
            signedUpAt: "2024-01-15T09:30:00Z",
        };
        server.mockEndpoint().get("/account/me").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.account.getAccountMe();
        expect(response).toEqual({
            monthlyCreditsBalanceUsd: 1.1,
            additionalCreditsBalanceUsd: 1.1,
            email: "email",
            name: "name",
            signedUpAt: "2024-01-15T09:30:00Z",
        });
    });
});
