/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Account } from "./api/resources/account/client/Client.js";
import { Tasks } from "./api/resources/tasks/client/Client.js";
import { Sessions } from "./api/resources/sessions/client/Client.js";
import { Files } from "./api/resources/files/client/Client.js";
import { Persistence } from "./api/resources/persistence/client/Client.js";

export declare namespace BrowserUseClient {
    export interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class BrowserUseClient {
    protected readonly _options: BrowserUseClient.Options;
    protected _account: Account | undefined;
    protected _tasks: Tasks | undefined;
    protected _sessions: Sessions | undefined;
    protected _files: Files | undefined;
    protected _persistence: Persistence | undefined;

    constructor(_options: BrowserUseClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "",
                    "X-Fern-SDK-Version": "0.0.25",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get account(): Account {
        return (this._account ??= new Account(this._options));
    }

    public get tasks(): Tasks {
        return (this._tasks ??= new Tasks(this._options));
    }

    public get sessions(): Sessions {
        return (this._sessions ??= new Sessions(this._options));
    }

    public get files(): Files {
        return (this._files ??= new Files(this._options));
    }

    public get persistence(): Persistence {
        return (this._persistence ??= new Persistence(this._options));
    }
}
